import type { Metadata } from "next";

import { Inter } from "next/font/google";

import "./globals.css";

import SideNavigationBar from "@/components/homeComponents/SideNavigationBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${inter.className} flex mx-auto max-w-7xl min-w-[1280px] bg-bg-100`}
      >
        <SideNavigationBar />
        {children}
      </body>
    </html>
  );
}
